# fly.toml app configuration file generated for code-pvp-api on 2026-04-13T15:41:54-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'code-pvp-api'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
